---
title: "R Notebook"
output: html_notebook
---

#install.packages("dplyr")
#install.packages("rjson")
#install.packages("RMySQL")
#install.packages("dbplyr")


## Connect to sql database
# Load libraries
library(dplyr)
library(rjson)
library(RMySQL)

# Read in credentials from provided JSON file

creds<- fromJSON(file="~/Downloads/rds_cred_walmart.json")

print(creds)

# Set up SQL server connection

mydb = dbConnect(MySQL(), dbname = creds$database, host = creds$url, port = creds$port, user = creds$user, password = creds$pass)

dbListTables(mydb)

# Request and download data

feats <- dbSendQuery(mydb, "SELECT * from features")

data = fetch(feats, n = -1)
head(data)

write.csv(data, file="walmart_features.csv")

sample <- dbSendQuery(mydb, "SELECT * from sampleSubmission")

data = fetch(sample, n = -1)
head(data)

write.csv(data, file="walmart_sample.csv")

stores <- dbSendQuery(mydb, "SELECT * from stores")

data = fetch(stores, n = -1)
head(data)

write.csv(data, file="walmart_stores.csv")

test <- dbSendQuery(mydb, "SELECT * from test")

data = fetch(test, n = -1)
head(data)

write.csv(data, file="walmart_test.csv")

train <- dbSendQuery(mydb, "SELECT * from train")

data = fetch(train, n = -1)
head(data)

write.csv(data, file="walmart_train.csv")


dbDisconnect(mydb)

